### PR TITLE
WIP: Feature.add missing examples

### PR DESCRIPTION
**Pull request by gimmins**
@dacast, @daviddacast

### CODE REVIEW

**Review by daviddacast — CHANGES_REQUESTED** [review]
Instead of 
 +        "originalFilename" => 'NAME OF YOUR FILENAME',
have 
 +        "originalFilename" => 'NAME OF YOUR FILE',

Instead of
$api = new \Dacast\Api('YOUR_DACAST_API')
have
$api = new \Dacast\Api('YOUR_APIKEY')

**Comment by gimmins** [comment]
@daviddacast, one more time please?

**Comment by gimmins** [comment]
Sorry I missed the other one, @daviddacast. One last review?

**Review by daviddacast — APPROVED** [review]
OK

**Pull request merged**
